name: approval-test
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  scan-and-evaluate:
    outputs:
      policy-subject: ${{ steps.gosec-step.outputs.policy-subject }}
    steps:
        - id: gosec-step
          uses: cloudbees-io/gosec-plugin@v1

        - name: Print policy input
          uses: docker://alpine:latest
          shell: sh
          env:
            ORG: ${{ cloudbees.org.id }}
            ACCESS_KEY: ${{ cloudbees.api.token }}
            URL: ${{ cloudbees.api.url }}
            POLICY_SUBJECT: ${{ steps.gosec-step.outputs.policy-subject }}
          run: |
            echo "$URL"
            echo "$ORG"
            echo "Authorization: Bearer $ACCESS_KEY"
            echo "$POLICY_SUBJECT"
  policy-evaluation:
    uses: cloudbees-io/policy-utils/evaluate-policy/workflow.yml@v0.1
    needs:
      - scan-and-evaluate
    with:
      policy-id: 9517fa03-035b-411c-a8d1-bafb4345697f
      input-data: ${{ needs.scan-and-evaluate.outputs.policy-subject }}